/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    FAvatar: typeof import('@fireflymit/ui/es/components/Avatar')['default']
    FBadge: typeof import('@fireflymit/ui/es/components/Badge')['default']
    FBanner: typeof import('@fireflymit/ui/es/components/Banner')['default']
    FCardBanner: typeof import('@fireflymit/ui/es/components/CardBanner')['default']
    FContextMenu: typeof import('@fireflymit/ui/es/components/ContextMenu')['default']
    FCountTo: typeof import('@fireflymit/ui/es/components/CountTo')['default']
    FDragVerify: typeof import('@fireflymit/ui/es/components/DragVerify')['default']
    FProForm: typeof import('@fireflymit/ui/es/components/ProForm')['default']
    FSearchBar: typeof import('@fireflymit/ui/es/components/SearchBar')['default']
    FSvgIcon: typeof import('@fireflymit/ui/es/components/SvgIcon')['default']
    FTextScroll: typeof import('@fireflymit/ui/es/components/TextScroll')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSpace: typeof import('element-plus/es')['ElSpace']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElText: typeof import('element-plus/es')['ElText']
  const FAvatar: typeof import('@fireflymit/ui/es/components/Avatar')['default']
  const FBadge: typeof import('@fireflymit/ui/es/components/Badge')['default']
  const FBanner: typeof import('@fireflymit/ui/es/components/Banner')['default']
  const FCardBanner: typeof import('@fireflymit/ui/es/components/CardBanner')['default']
  const FContextMenu: typeof import('@fireflymit/ui/es/components/ContextMenu')['default']
  const FCountTo: typeof import('@fireflymit/ui/es/components/CountTo')['default']
  const FDragVerify: typeof import('@fireflymit/ui/es/components/DragVerify')['default']
  const FProForm: typeof import('@fireflymit/ui/es/components/ProForm')['default']
  const FSearchBar: typeof import('@fireflymit/ui/es/components/SearchBar')['default']
  const FSvgIcon: typeof import('@fireflymit/ui/es/components/SvgIcon')['default']
  const FTextScroll: typeof import('@fireflymit/ui/es/components/TextScroll')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}