import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compileString } from 'sass'
import { describe, expect, it } from 'vitest'
import { createNamespace } from '../_utils'

const __dirname = dirname(fileURLToPath(import.meta.url))

describe('styles namespace', () => {
  it('matches the BEM namespace generated by createNamespace', () => {
    const [className, bem] = createNamespace('button')
    const result = compileString(
      `
        @use "styles/mixins" as *;

        @include b(button) {
          @include e(icon) {
            color: red;
          }

          @include m(primary) {
            color: blue;
          }
        }
      `,
      {
        loadPaths: [
          resolve(__dirname, '..'),
          resolve(__dirname, '../../node_modules'),
          resolve(__dirname, '../../../..', 'node_modules'),
        ],
      },
    )

    expect(result.css).toContain(`.${bem('__icon')}`)
    expect(result.css).toContain(`.${bem('primary')}`)
    expect(result.css).toContain(`.${className}`)
    expect(result.css).not.toContain('.yh-button')
  })
})
